on:
  pull_request:
    types:
      - closed

jobs:
  delete:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Delete Cloudflare Pages deployments'
        uses: unlike-ltd/github-actions-cloudflare-pages@v1.0.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: preview-deploy
          directory: '/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: preview-deploy ${{ (github.ref == 'refs/heads/main' && '(Production)') || '(Preview)' }}
